// <auto-generated />
using System;
using BEARFLIX.Models.BD;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BEARFLIX.Migrations
{
    [DbContext(typeof(BearflixContext))]
    partial class BearflixContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BEARFLIX.Models.BD.Banco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("PK__Banco__3213E83F0CDF7A3E");

                    b.HasIndex(new[] { "Descripcion" }, "UQ__Banco__298336B6A846EEF5")
                        .IsUnique();

                    b.ToTable("Banco");
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("PK__Genero__3213E83FE0FDFB64");

                    b.HasIndex(new[] { "Descripcion" }, "UQ__Genero__298336B6535391E6")
                        .IsUnique();

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.Pelicula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<int>("Duracion")
                        .HasColumnType("int")
                        .HasColumnName("duracion");

                    b.Property<string>("Fondo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("fondo");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    b.Property<string>("Portada")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("portada");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio_compra");

                    b.Property<decimal>("PrecioRenta")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio_renta");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("titulo");

                    b.Property<string>("TituloImagen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("titulo_imagen");

                    b.Property<string>("Video")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("video");

                    b.HasKey("Id")
                        .HasName("PK__Pelicula__3213E83F8744204E");

                    b.HasIndex("IdProveedor");

                    b.HasIndex(new[] { "Titulo" }, "UQ__Pelicula__38FA640FCFB2E8C2")
                        .IsUnique();

                    b.HasIndex(new[] { "Titulo" }, "idx_pelicula_titulo");

                    b.ToTable("Pelicula");
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("PK__Permiso__3213E83F368A8851");

                    b.HasIndex(new[] { "Descripcion" }, "UQ__Permiso__298336B64EE0242F")
                        .IsUnique();

                    b.ToTable("Permiso");
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion");

                    b.Property<byte>("Porcentaje")
                        .HasColumnType("tinyint")
                        .HasColumnName("porcentaje");

                    b.HasKey("Id")
                        .HasName("PK__Proveedo__3213E83F8ECC1BBF");

                    b.HasIndex(new[] { "Descripcion" }, "UQ__Proveedo__298336B608C3003C")
                        .IsUnique();

                    b.HasIndex(new[] { "Descripcion" }, "idx_proveedor_descripcion");

                    b.ToTable("Proveedor");
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.Puntaje", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IdPelicula")
                        .HasColumnType("int")
                        .HasColumnName("id_pelicula");

                    b.Property<byte>("Puntaje1")
                        .HasColumnType("tinyint")
                        .HasColumnName("puntaje");

                    b.HasKey("IdUsuario", "IdPelicula")
                        .HasName("PK__Puntaje__856E135946915967");

                    b.HasIndex("IdPelicula");

                    b.HasIndex(new[] { "IdUsuario", "Puntaje1" }, "idx_puntaje_usuario");

                    b.ToTable("Puntaje");
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaGeneracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_generacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("GananciasBrutas")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("ganancias_brutas");

                    b.Property<decimal>("GananciasTotales")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("ganancias_totales");

                    b.Property<DateOnly>("RangoFin")
                        .HasColumnType("date")
                        .HasColumnName("rango_fin");

                    b.Property<DateOnly>("RangoInicio")
                        .HasColumnType("date")
                        .HasColumnName("rango_inicio");

                    b.HasKey("Id")
                        .HasName("PK__Reporte__3213E83F5DC71BCC");

                    b.ToTable("Reporte");
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.ReporteProveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    b.Property<int>("IdReporte")
                        .HasColumnType("int")
                        .HasColumnName("id_reporte");

                    b.Property<int>("IdTipo")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo");

                    b.Property<decimal>("MontoAPagar")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("monto_a_pagar");

                    b.Property<decimal>("TotalGanancias")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("total_ganancias");

                    b.HasKey("Id")
                        .HasName("PK__ReporteP__3213E83F9CF1B662");

                    b.HasIndex("IdTipo");

                    b.HasIndex(new[] { "IdReporte", "IdProveedor", "IdTipo" }, "UQ__ReporteP__97F8BA38AAB4AB51")
                        .IsUnique();

                    b.HasIndex(new[] { "IdProveedor", "IdTipo" }, "idx_reporte_proveedor_tipo");

                    b.ToTable("ReporteProveedor");
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("PK__Rol__3213E83F867DD8B6");

                    b.HasIndex(new[] { "Descripcion" }, "UQ__Rol__298336B6F6AF6237")
                        .IsUnique();

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.Tarjeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdBanco")
                        .HasColumnType("int")
                        .HasColumnName("id_banco");

                    b.Property<int>("IdTipo")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numero");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("titular");

                    b.Property<string>("UltimosCuatro")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("ultimos_cuatro");

                    b.Property<DateOnly>("Vencimiento")
                        .HasColumnType("date")
                        .HasColumnName("vencimiento");

                    b.HasKey("Id")
                        .HasName("PK__Tarjeta__3213E83F307CD1CA");

                    b.HasIndex("IdBanco");

                    b.HasIndex("IdTipo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Tarjeta");
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.TipoTarjeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("PK__TipoTarj__3213E83F3CCAC959");

                    b.HasIndex(new[] { "Descripcion" }, "UQ__TipoTarj__298336B67DC1FCCB")
                        .IsUnique();

                    b.ToTable("TipoTarjeta");
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.TipoVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("PK__TipoVent__3213E83F0D45F75B");

                    b.HasIndex(new[] { "Descripcion" }, "UQ__TipoVent__298336B652AE8540")
                        .IsUnique();

                    b.ToTable("TipoVenta");
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_baja");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Foto")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("foto");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex(new[] { "Email" }, "UQ__Usuario__2A586E0B4FD6CE3F")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Expiracion")
                        .HasColumnType("datetime")
                        .HasColumnName("expiracion");

                    b.Property<DateTime>("FechaVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_venta")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdPelicula")
                        .HasColumnType("int")
                        .HasColumnName("id_pelicula");

                    b.Property<int>("IdTipo")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("monto");

                    b.HasKey("Id")
                        .HasName("PK__Venta__3213E83F20DB1106");

                    b.HasIndex(new[] { "FechaVenta" }, "idx_venta_fecha");

                    b.HasIndex(new[] { "IdPelicula" }, "idx_venta_pelicula");

                    b.HasIndex(new[] { "IdTipo" }, "idx_venta_tipo");

                    b.HasIndex(new[] { "IdUsuario" }, "idx_venta_usuario");

                    b.ToTable("Venta");
                });

            modelBuilder.Entity("GeneroPelicula", b =>
                {
                    b.Property<int>("IdGenero")
                        .HasColumnType("int");

                    b.Property<int>("IdPelicula")
                        .HasColumnType("int");

                    b.HasKey("IdGenero", "IdPelicula");

                    b.ToTable("GeneroPelicula");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PeliculaGenero", b =>
                {
                    b.Property<int>("IdPelicula")
                        .HasColumnType("int")
                        .HasColumnName("id_pelicula");

                    b.Property<int>("IdGenero")
                        .HasColumnType("int")
                        .HasColumnName("id_genero");

                    b.HasKey("IdPelicula", "IdGenero")
                        .HasName("PK__Pelicula__3C9BF10288C9D129");

                    b.HasIndex(new[] { "IdGenero" }, "idx_pelicula_genero");

                    b.ToTable("PeliculaGenero");
                });

            modelBuilder.Entity("PermisoRol", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("int")
                        .HasColumnName("id_permiso");

                    b.HasKey("IdRol", "IdPermiso")
                        .HasName("PK__PermisoR__889447C48067D7CB");

                    b.HasIndex("IdPermiso");

                    b.ToTable("PermisoRol");
                });

            modelBuilder.Entity("RolUsuario", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdRol", "IdUsuario");

                    b.ToTable("RolUsuario");
                });

            modelBuilder.Entity("UsuarioRol", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.HasKey("IdUsuario", "IdRol")
                        .HasName("PK__UsuarioR__5895CFF38AC7C735");

                    b.HasIndex("IdRol");

                    b.ToTable("UsuarioRol");
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.Pelicula", b =>
                {
                    b.HasOne("BEARFLIX.Models.BD.Proveedor", "IdProveedorNavigation")
                        .WithMany("Pelicula")
                        .HasForeignKey("IdProveedor")
                        .IsRequired()
                        .HasConstraintName("FK__Pelicula__id_pro__5441852A");

                    b.Navigation("IdProveedorNavigation");
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.Puntaje", b =>
                {
                    b.HasOne("BEARFLIX.Models.BD.Pelicula", "IdPeliculaNavigation")
                        .WithMany("Puntaje")
                        .HasForeignKey("IdPelicula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Puntaje__id_peli__6FE99F9F");

                    b.HasOne("BEARFLIX.Models.BD.Usuario", "IdUsuarioNavigation")
                        .WithMany("Puntaje")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Puntaje__id_usua__6EF57B66");

                    b.Navigation("IdPeliculaNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.ReporteProveedor", b =>
                {
                    b.HasOne("BEARFLIX.Models.BD.Proveedor", "IdProveedorNavigation")
                        .WithMany("ReporteProveedor")
                        .HasForeignKey("IdProveedor")
                        .IsRequired()
                        .HasConstraintName("FK__ReportePr__id_pr__778AC167");

                    b.HasOne("BEARFLIX.Models.BD.Reporte", "IdReporteNavigation")
                        .WithMany("ReporteProveedor")
                        .HasForeignKey("IdReporte")
                        .IsRequired()
                        .HasConstraintName("FK__ReportePr__id_re__76969D2E");

                    b.HasOne("BEARFLIX.Models.BD.TipoVenta", "IdTipoNavigation")
                        .WithMany("ReporteProveedor")
                        .HasForeignKey("IdTipo")
                        .IsRequired()
                        .HasConstraintName("FK__ReportePr__id_ti__787EE5A0");

                    b.Navigation("IdProveedorNavigation");

                    b.Navigation("IdReporteNavigation");

                    b.Navigation("IdTipoNavigation");
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.Tarjeta", b =>
                {
                    b.HasOne("BEARFLIX.Models.BD.Banco", "IdBancoNavigation")
                        .WithMany("Tarjeta")
                        .HasForeignKey("IdBanco")
                        .IsRequired()
                        .HasConstraintName("FK__Tarjeta__id_banc__5DCAEF64");

                    b.HasOne("BEARFLIX.Models.BD.TipoTarjeta", "IdTipoNavigation")
                        .WithMany("Tarjeta")
                        .HasForeignKey("IdTipo")
                        .IsRequired()
                        .HasConstraintName("FK__Tarjeta__id_tipo__5EBF139D");

                    b.HasOne("BEARFLIX.Models.BD.Usuario", "IdUsuarioNavigation")
                        .WithMany("Tarjeta")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Tarjeta__id_usua__5FB337D6");

                    b.Navigation("IdBancoNavigation");

                    b.Navigation("IdTipoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.Venta", b =>
                {
                    b.HasOne("BEARFLIX.Models.BD.Pelicula", "IdPeliculaNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdPelicula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Venta__id_pelicu__59063A47");

                    b.HasOne("BEARFLIX.Models.BD.TipoVenta", "IdTipoNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdTipo")
                        .IsRequired()
                        .HasConstraintName("FK__Venta__id_tipo__59FA5E80");

                    b.HasOne("BEARFLIX.Models.BD.Usuario", "IdUsuarioNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Venta__id_usuari__5812160E");

                    b.Navigation("IdPeliculaNavigation");

                    b.Navigation("IdTipoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("BEARFLIX.Models.BD.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("BEARFLIX.Models.BD.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BEARFLIX.Models.BD.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("BEARFLIX.Models.BD.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeliculaGenero", b =>
                {
                    b.HasOne("BEARFLIX.Models.BD.Genero", null)
                        .WithMany()
                        .HasForeignKey("IdGenero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PeliculaG__id_ge__6B24EA82");

                    b.HasOne("BEARFLIX.Models.BD.Pelicula", null)
                        .WithMany()
                        .HasForeignKey("IdPelicula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PeliculaG__id_pe__6A30C649");
                });

            modelBuilder.Entity("PermisoRol", b =>
                {
                    b.HasOne("BEARFLIX.Models.BD.Permiso", null)
                        .WithMany()
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PermisoRo__id_pe__6754599E");

                    b.HasOne("BEARFLIX.Models.BD.Rol", null)
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PermisoRo__id_ro__66603565");
                });

            modelBuilder.Entity("UsuarioRol", b =>
                {
                    b.HasOne("BEARFLIX.Models.BD.Rol", null)
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UsuarioRo__id_ro__6383C8BA");

                    b.HasOne("BEARFLIX.Models.BD.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UsuarioRo__id_us__628FA481");
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.Banco", b =>
                {
                    b.Navigation("Tarjeta");
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.Pelicula", b =>
                {
                    b.Navigation("Puntaje");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.Proveedor", b =>
                {
                    b.Navigation("Pelicula");

                    b.Navigation("ReporteProveedor");
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.Reporte", b =>
                {
                    b.Navigation("ReporteProveedor");
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.TipoTarjeta", b =>
                {
                    b.Navigation("Tarjeta");
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.TipoVenta", b =>
                {
                    b.Navigation("ReporteProveedor");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("BEARFLIX.Models.BD.Usuario", b =>
                {
                    b.Navigation("Puntaje");

                    b.Navigation("Tarjeta");

                    b.Navigation("Venta");
                });
#pragma warning restore 612, 618
        }
    }
}
